In [1]:
# Importing liberaries.
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

In [18]:
import warnings
warnings.filterwarnings('ignore') # Ignoring warnings.

In [19]:
# Creating data frame.
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [20]:
# Creating new variable 'target'.
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [21]:
# Sepertaing independent & dependent variable.
x = df.drop('target',axis=1)
y = df['target']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
# Splitting into train & test dataset.
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [24]:
len(x_train),len(y_test)

(120, 30)

In [25]:
from sklearn.linear_model import LogisticRegression # Improting Logistic Regression

In [26]:
from sklearn.svm import SVC # improting Support Vector Machine.

In [27]:
from sklearn.tree import DecisionTreeClassifier # Importing Decision Tree Classifier.

In [28]:
from sklearn.ensemble import RandomForestClassifier # Importing Random Forest Classifier.

In [29]:
from sklearn.model_selection import cross_val_score # Importing Cross Validation Score

In [30]:
score = cross_val_score(LogisticRegression(),iris.data,iris.target,cv=10) # Cross_val_score of Logistic Regression.
score

array([1.        , 0.93333333, 1.        , 1.        , 0.93333333,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [32]:
np.average(score) # Average of score.

0.9733333333333334

In [48]:
score1 = cross_val_score(SVC(C=15),iris.data,iris.target,cv=10) # Cross_val_score of support vector machine.
score1

array([1.        , 0.93333333, 1.        , 1.        , 0.93333333,
       1.        , 0.93333333, 1.        , 1.        , 1.        ])

In [49]:
np.average(score1) # average of score

0.9800000000000001

In [44]:
score2 = cross_val_score(DecisionTreeClassifier(max_depth=5),iris.data,iris.target,cv=10)
# Cross_val_score of Decision Tree Classifier.
score2

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.86666667, 0.93333333, 1.        , 1.        , 1.        ])

In [45]:
np.average(score2) # Average of score.

0.96

In [58]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=15),iris.data,iris.target,cv=10)
# Cross_val_score of Random Forest Classifier.
score3

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [59]:
np.average(score3) # Average of score.

0.9666666666666666

  SVM is best performig model among above four model.

In [63]:
#Tunning model for C=15
model = SVC(C=15)
model.fit(x_train,y_train)

SVC(C=15)

In [64]:
model.score(x_test,y_test)

0.9666666666666667

In [65]:
model.predict([[5.0,3.6,1.4,0.2]])

array([0])